export const MQTT_CONNECT_SUCCESS = 'MQTT_CONNECT_SUCCESS'
export const MQTT_CONNECT_FAILURE = 'MQTT_CONNECT_FAILURE'
export const MQTT_SUBSCRIBE_SUCCESS = 'MQTT_SUBSCRIBE_SUCCESS'
export const MQTT_SUBSCRIBE_FAILURE = 'MQTT_SUBSCRIBE_FAILURE'
export const MQTT_RECIEVE_MESSAGE = 'MQTT_RECIEVE_MESSAGE'
export const MQTT_RECIEVE_MESSAGE_MOTION = 'MQTT_RECIEVE_MESSAGE_MOTION'

export const FETCH_NOTIFICATION_SUCCESS = 'FETCH_NOTIFICATION_SUCCESS'
export const FETCH_NOTIFICATIONS_REQUET = 'FETCH_NOTIFICATION_REQUET'
export const FETCH_NOTIFICATION_FAILURE = 'FETCH_NOTIFICATION_FAILURE'

export const FETCH_SMART_BOX_SUCCESS = 'FETCH_SMART_BOX_SUCCESS'
export const FETCH_SMART_BOX_REQUET = 'FETCH_SMART_BOX_REQUET'
export const FETCH_SMART_BOX_FAILURE = 'FETCH_SMART_BOX_FAILURE'