export const MQTT_CONNECT = 'MQTT_CONNECT'
export const MQTT_SUBSCRIBE_SUCCESS = 'MQTT_SUBSCRIBE_SUCCESS'
export const MQTT_SEND_SUCCESS = 'MQTT_SEND_SUCCESS'
export const MQTT_FAILD = 'MQTT_SEND_SUCCESS'